name: Python Script Execution

on:
  push:
    branches:
      - main

jobs:
  run_python_script:
    name: Run Python script
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository's code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies if needed

      - name: Execute Python script
        run: python Test_runner.py
